@startuml
left to right direction
skinparam linetype ortho
hide circle

entity user {
  +id: int <<PK>>
  --
  +username: str
  +password_hash: str
}

entity game {
  +id: int <<PK>>
  --
  +rounds: int
  +start_time: int
  +end_time: int
}

entity user_game {
  +user: int <<FK>> <<PK>>
  +game: int <<FK>> <<PK>>
  --
  +buy_ins: int
  +hands_won: int
  +total_investment: int
  +final_balance: int
}

entity round {
  +id: int <<PK>>
  --
  +timesstamp: int
  +game: int <<FK>>
  +community_cards: str
  +winner: int <<FK>>
  +pot: int
  +hand_type: str
}

entity round_hand {
  +id: int <<PK>>
  --
  +round: int <<FK>>
  +user: int <<FK>>
  +cards: str
  +hand_type: str
  +final_action: str
  +contributed: int
}

user ||--o{ user_game
user_game }o--|| game
round }o--|| game
round_hand }o--|| round
round_hand }o--|| user
round }o--|| user
@enduml
